name: Reusable CI Workflow

on:
  workflow_call:
    outputs:
      fullSemVersion: 
        description: 'The calculated full semantic version of the build'
        value: ${{ jobs.build.outputs.fullSemVerOutput }}
      

jobs:
  build:
    runs-on: windows-latest
    
    setps:
      - name: Checkout
        uses: action/checkout@v3
        with:
          fetch-depth: 0
          
      # Install gitversion tool
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: '5.x'
          
      # Determine gitversion
      - name: Determine GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.13
        
      # Map gitversion to an output, note: for running in powershell, use $env:GITHUB_OUTPUT, in bash use $GITHUB_OUTPUT
      - name: Map GitVersion
        id: mapgitversion
        run: echo "fullSemVersion=${{ steps.gitversion.outputs.fullSemVer }}" >> $env:GITHUB_OUTPUT
