name: CI CD Entry Workflow
on:
  workflow_dispatch:

jobs:
  build:
    uses: FuBoyang/workflow-templates/.github/workflows/ci-reusable.yml@feat/dev
    secrets: inherit
          
         
  release:
    strategy:
      matrix:
        releaseenv: [DEV_1, UAT]
    needs: build
    uses: FuBoyang/workflow-templates/.github/workflows/cd-reusable.yml@feat/dev
    with:
      environment: ${{ matrix.releaseenv }}
      input1: '${{ needs.build.outputs.buildoutput }}'
