name: CI CD Entry Workflow
on:
  workflow_dispatch:

jobs:
  build:
#     uses: ./.github/workflows/ci-test.yml
    uses: FuBoyang/workflow-templates/.github/workflows/ci-reusable.yml@feat/dev
   
#   release:
#     uses: ./.github/workflows/cd-test.yml
    
